/**
 * Super-admin Invoices.
 *
 * Read-only by default — invoices are generated by the system on
 * subscription periods, payments, and approved custom-requirement
 * tickets. Admin can manually mark an invoice paid (e.g. after a
 * direct bank transfer outside Cashfree) or void.
 */
const control = require('../../control/db');
const { requireSuperAdmin } = require('./superAdminAuth');

async function api_saas_invoices_list(token, filters) {
  await requireSuperAdmin(token);
  const f = filters || {};
  const where = [];
  const params = [];
  if (f.tenant_id) { params.push(f.tenant_id); where.push(`i.tenant_id = $${params.length}`); }
  if (f.status)    { params.push(f.status);    where.push(`i.status = $${params.length}`); }
  if (f.from)      { params.push(f.from);      where.push(`i.created_at >= $${params.length}`); }
  if (f.to)        { params.push(f.to);        where.push(`i.created_at <= $${params.length}`); }
  const sql = `
    SELECT i.*, t.slug, t.org_name, t.contact_email, p.name AS package_name
      FROM invoices i
      LEFT JOIN tenants t ON t.id = i.tenant_id
      LEFT JOIN packages p ON p.id = i.package_id
     ${where.length ? 'WHERE ' + where.join(' AND ') : ''}
     ORDER BY i.id DESC LIMIT 1000`;
  const r = await control.query(sql, params);
  return r.rows;
}

async function api_saas_invoices_get(token, id) {
  await requireSuperAdmin(token);
  const r = await control.query(
    `SELECT i.*, t.slug, t.org_name, t.contact_email, t.contact_name,
            t.contact_mobile, p.name AS package_name
       FROM invoices i
       LEFT JOIN tenants t ON t.id = i.tenant_id
       LEFT JOIN packages p ON p.id = i.package_id
      WHERE i.id = $1`,
    [id]
  );
  return r.rows[0] || null;
}

async function api_saas_invoices_markPaid(token, id) {
  const me = await requireSuperAdmin(token);
  const inv = await control.findById('invoices', id);
  if (!inv) throw new Error('Invoice not found');
  if (inv.status === 'paid') return { ok: true };
  await control.update('invoices', id, { status: 'paid', paid_at: control.nowIso() });
  await control.insert('audit_log', {
    actor_type: 'super_admin', actor_id: me.id, actor_email: me.email,
    tenant_id: inv.tenant_id, event: 'invoice.marked_paid',
    detail: JSON.stringify({ invoice_id: id, number: inv.number, total: inv.total_inr })
  });
  return { ok: true };
}

async function api_saas_invoices_void(token, id) {
  const me = await requireSuperAdmin(token);
  const inv = await control.findById('invoices', id);
  if (!inv) throw new Error('Invoice not found');
  await control.update('invoices', id, { status: 'void' });
  await control.insert('audit_log', {
    actor_type: 'super_admin', actor_id: me.id, actor_email: me.email,
    tenant_id: inv.tenant_id, event: 'invoice.voided',
    detail: JSON.stringify({ invoice_id: id, number: inv.number })
  });
  return { ok: true };
}

module.exports = {
  api_saas_invoices_list,
  api_saas_invoices_get,
  api_saas_invoices_markPaid,
  api_saas_invoices_void
};
