/**
 * Super-admin Invoices.
 *
 * Read-only by default — invoices are generated by the system on
 * subscription periods, payments, and approved custom-requirement
 * tickets. Admin can manually mark an invoice paid (e.g. after a
 * direct bank transfer outside Cashfree) or void.
 */
const control = require('../../control/db');
const { requireSuperAdmin } = require('./superAdminAuth');

async function api_saas_invoices_list(token, filters) {
  await requireSuperAdmin(token);
  const f = filters || {};
  const where = [];
  const params = [];
  if (f.tenant_id) { params.push(f.tenant_id); where.push(`i.tenant_id = $${params.length}`); }
  if (f.status)    { params.push(f.status);    where.push(`i.status = $${params.length}`); }
  if (f.from)      { params.push(f.from);      where.push(`i.created_at >= $${params.length}`); }
  if (f.to)        { params.push(f.to);        where.push(`i.created_at <= $${params.length}`); }
  const sql = `
    SELECT i.*, t.slug, t.org_name, t.contact_email, p.name AS package_name
      FROM invoices i
      LEFT JOIN tenants t ON t.id = i.tenant_id
      LEFT JOIN packages p ON p.id = i.package_id
     ${where.length ? 'WHERE ' + where.join(' AND ') : ''}
     ORDER BY i.id DESC LIMIT 1000`;
  const r = await control.query(sql, params);
  return r.rows;
}

async function api_saas_invoices_get(token, id) {
  await requireSuperAdmin(token);
  const r = await control.query(
    `SELECT i.*, t.slug, t.org_name, t.contact_email, t.contact_name,
            t.contact_mobile, p.name AS package_name
       FROM invoices i
       LEFT JOIN tenants t ON t.id = i.tenant_id
       LEFT JOIN packages p ON p.id = i.package_id
      WHERE i.id = $1`,
    [id]
  );
  return r.rows[0] || null;
}

async function api_saas_invoices_markPaid(token, id) {
  const me = await requireSuperAdmin(token);
  const inv = await control.findById('invoices', id);
  if (!inv) throw new Error('Invoice not found');
  if (inv.status === 'paid') return { ok: true };
  await control.update('invoices', id, { status: 'paid', paid_at: control.nowIso() });
  await control.insert('audit_log', {
    actor_type: 'super_admin', actor_id: me.id, actor_email: me.email,
    tenant_id: inv.tenant_id, event: 'invoice.marked_paid',
    detail: JSON.stringify({ invoice_id: id, number: inv.number, total: inv.total_inr })
  });
  return { ok: true };
}

async function api_saas_invoices_void(token, id) {
  const me = await requireSuperAdmin(token);
  const inv = await control.findById('invoices', id);
  if (!inv) throw new Error('Invoice not found');
  await control.update('invoices', id, { status: 'void' });
  await control.insert('audit_log', {
    actor_type: 'super_admin', actor_id: me.id, actor_email: me.email,
    tenant_id: inv.tenant_id, event: 'invoice.voided',
    detail: JSON.stringify({ invoice_id: id, number: inv.number })
  });
  return { ok: true };
}


/* ---------------- SAAS_AUTO_INVOICE_v1 (2026-06-27) ---------------- */

async function api_saas_invoices_create(token, payload) {
  const { requireFullAdmin } = require('./superAdminAuth');
  const me = await requireFullAdmin(token);
  const p = payload || {};
  if (!p.tenant_id) throw new Error('tenant_id required');
  const tr = await control.query(`SELECT id, org_name AS name, package_id, current_period_start, current_period_end FROM tenants WHERE id=$1`, [p.tenant_id]);
  if (!tr.rows.length) throw new Error('Tenant not found');
  const t = tr.rows[0];
  const subtotal = Number(p.subtotal_inr) || 0;
  const tax      = p.tax_inr !== undefined ? Number(p.tax_inr) : Math.round(subtotal * 18) / 100;
  const total    = Math.round((subtotal + tax) * 100) / 100;
  const ag = require('../../utils/saasInvoiceAutoGen');
  const number = p.number || (await ag._genInvoiceNumber());
  const ins = await control.query(
    `INSERT INTO invoices (tenant_id, number, package_id, description, subtotal_inr, tax_inr, total_inr,
                           period_start, period_end, status, notes, created_at, updated_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending',$10, NOW(), NOW()) RETURNING id, number`,
    [t.id, number, t.package_id || p.package_id || null, p.description || 'Subscription invoice',
     subtotal, tax, total,
     p.period_start || t.current_period_start || new Date(Date.now()-30*86400000).toISOString(),
     p.period_end   || t.current_period_end   || new Date().toISOString(),
     'Created manually by ' + me.email]
  );
  return { ok: true, id: ins.rows[0].id, number: ins.rows[0].number, total };
}

async function api_saas_invoices_send(token, payload) {
  const { requireFullAdmin } = require('./superAdminAuth');
  await requireFullAdmin(token);
  const p = payload || {};
  if (!p.id) throw new Error('id required');
  const channels = {
    email:    p.email    === true || p.email    === 1 || p.email    === '1',
    whatsapp: p.whatsapp === true || p.whatsapp === 1 || p.whatsapp === '1'
  };
  if (!channels.email && !channels.whatsapp) throw new Error('At least one channel (email or whatsapp) must be true');
  const r = await control.query(
    `SELECT i.id, i.number, i.total_inr, i.subtotal_inr, i.tax_inr, i.period_end, i.description AS package_name,
            t.id AS tenant_id, t.org_name AS tenant_name, t.contact_email, t.contact_mobile AS contact_phone
       FROM invoices i JOIN tenants t ON t.id = i.tenant_id
      WHERE i.id = $1`, [p.id]);
  if (!r.rows.length) throw new Error('Invoice not found');
  const row = r.rows[0];
  const tenant = { id: row.tenant_id, name: row.tenant_name, contact_email: row.contact_email, contact_phone: row.contact_phone };
  const invoice = { id: row.id, number: row.number, total: row.total_inr, subtotal: row.subtotal_inr, tax: row.tax_inr,
                    periodEnd: row.period_end, packageName: row.package_name };
  const ag = require('../../utils/saasInvoiceAutoGen');
  const out = await ag._sendInvoice(tenant, invoice, channels);
  return { ok: true, sent: out };
}

async function api_saas_invoices_runAutoGen(token) {
  const { requireFullAdmin } = require('./superAdminAuth');
  await requireFullAdmin(token);
  const ag = require('../../utils/saasInvoiceAutoGen');
  return await ag.runOnce();
}

module.exports = {
  api_saas_invoices_list,
  api_saas_invoices_get,
  api_saas_invoices_markPaid,
  api_saas_invoices_void,
  api_saas_invoices_create,
  api_saas_invoices_send,
  api_saas_invoices_runAutoGen
};
