/* ============================================================================
 * SaaS auto-invoice generator + dispatcher (SAAS_AUTO_INVOICE_v1, 2026-06-27)
 *
 * Daily sweep:
 *   1. Find every active tenant with current_period_end within
 *      AUTO_INVOICE_DAYS_BEFORE (default 7).
 *   2. If no pending/paid invoice already covers that period_end, create one.
 *   3. If AUTO_INVOICE_SEND_EMAIL / _SEND_WA = '1', send via that channel.
 *
 * Load-safe: zero work unless AUTO_INVOICE_DAYS_BEFORE > 0.
 * Idempotent: never duplicates invoices for the same period_end.
 * ============================================================================ */
'use strict';
const control     = require('../control/db');
const saasMailer  = require('../routes/saas/saasMailer');
const saasWA      = require('../routes/saas/saasWhatsApp');

const RUN_EVERY_MS = 6 * 60 * 60 * 1000;  // 6 hours

let _started = false;
let _running = false;

function _fmtINR(n) {
  return '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function _fmtDate(d) {
  if (!d) return '—';
  try { return new Date(d).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }); }
  catch (_) { return String(d); }
}

async function _genInvoiceNumber() {
  const yr = new Date().getFullYear();
  const r = await control.query(
    `SELECT number FROM invoices WHERE number LIKE $1 ORDER BY id DESC LIMIT 1`,
    [`INV-${yr}-%`]
  );
  let next = 1;
  if (r.rows.length) {
    const m = String(r.rows[0].number).match(/(\d+)$/);
    if (m) next = parseInt(m[1], 10) + 1;
  }
  return `INV-${yr}-${String(next).padStart(6, '0')}`;
}

async function _createInvoiceForTenant(t) {
  // Find the package to get amount
  let amount = 0, pkgName = 'Subscription';
  if (t.package_id) {
    const p = await control.query(`SELECT name, price_inr FROM packages WHERE id=$1`, [t.package_id]);
    if (p.rows.length) { amount = Number(p.rows[0].price_inr) || 0; pkgName = p.rows[0].name; }
  }
  const tax = Math.round(amount * 18) / 100;  // 18% GST
  const total = Math.round((amount + tax) * 100) / 100;
  const number = await _genInvoiceNumber();
  const periodStart = t.current_period_start || new Date(Date.now() - 30*86400000).toISOString();
  const periodEnd   = t.current_period_end   || new Date().toISOString();
  const ins = await control.query(
    `INSERT INTO invoices
       (tenant_id, number, package_id, description, subtotal_inr, tax_inr, total_inr,
        period_start, period_end, status, notes, created_at, updated_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending',$10, NOW(), NOW())
     RETURNING id, number`,
    [t.id, number, t.package_id || null, pkgName + ' — renewal', amount, tax, total,
     periodStart, periodEnd, 'Auto-generated by SAAS_AUTO_INVOICE_v1']
  );
  return { id: ins.rows[0].id, number: ins.rows[0].number, total, subtotal: amount, tax,
           periodEnd, packageName: pkgName };
}

function _emailHtml({ tenant, invoice, platform }) {
  return `<div style="font-family:Inter,system-ui,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#1c1917">
    <div style="background:linear-gradient(135deg,#7c3aed,#a855f7);padding:20px;border-radius:10px 10px 0 0;color:#fff">
      <h2 style="margin:0">Invoice ${invoice.number}</h2>
      <p style="margin:6px 0 0;opacity:.9">${platform.name || 'SmartCRM'} subscription renewal</p>
    </div>
    <div style="background:#fff;border:1px solid #ddd6fe;border-top:0;border-radius:0 0 10px 10px;padding:20px">
      <p>Hi ${tenant.name || 'there'},</p>
      <p>Your <b>${platform.name || 'SmartCRM'}</b> subscription is up for renewal. Please find the invoice details below:</p>
      <table style="width:100%;border-collapse:collapse;margin:14px 0">
        <tr><td style="padding:8px;border-bottom:1px solid #eee">Package</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right"><b>${invoice.packageName}</b></td></tr>
        <tr><td style="padding:8px;border-bottom:1px solid #eee">Period</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right">till ${_fmtDate(invoice.periodEnd)}</td></tr>
        <tr><td style="padding:8px;border-bottom:1px solid #eee">Subtotal</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${_fmtINR(invoice.subtotal)}</td></tr>
        <tr><td style="padding:8px;border-bottom:1px solid #eee">GST (18%)</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${_fmtINR(invoice.tax)}</td></tr>
        <tr><td style="padding:12px 8px;font-size:16px"><b>Total Due</b></td><td style="padding:12px 8px;text-align:right;font-size:18px;color:#7c3aed"><b>${_fmtINR(invoice.total)}</b></td></tr>
      </table>
      <p style="background:#fef3c7;border-left:3px solid #f59e0b;padding:10px;border-radius:4px;color:#92400e">
        ⏰ Due by ${_fmtDate(invoice.periodEnd)}. Please pay before then to avoid service interruption.
      </p>
      <p style="color:#78716c;font-size:13px;margin-top:20px">
        Questions? Reply to this email or call ${platform.supportPhone || 'support'}.
      </p>
    </div>
  </div>`;
}

async function _sendInvoice(tenant, invoice, channels) {
  const platform = {
    name:         (await control.getSetting('PLATFORM_NAME')) || 'SmartCRM',
    supportPhone: (await control.getSetting('SUPPORT_PHONE')) || '',
    supportEmail: (await control.getSetting('SUPPORT_EMAIL')) || ''
  };
  const out = { email: null, whatsapp: null };
  if (channels.email && tenant.contact_email) {
    try {
      await saasMailer.sendMail({
        to: tenant.contact_email,
        subject: `Invoice ${invoice.number} — ${platform.name} renewal (${_fmtINR(invoice.total)})`,
        html: _emailHtml({ tenant, invoice, platform })
      });
      out.email = 'sent';
    } catch (e) {
      out.email = 'err: ' + e.message;
    }
  }
  if (channels.whatsapp && tenant.contact_phone) {
    try {
      await saasWA.sendTemplate({
        to: tenant.contact_phone,
        params: [
          tenant.name || 'Customer',
          invoice.number,
          _fmtINR(invoice.total),
          _fmtDate(invoice.periodEnd)
        ]
      });
      out.whatsapp = 'sent';
    } catch (e) {
      out.whatsapp = 'err: ' + e.message;
    }
  }
  // Log to invoice notes
  try {
    const stamp = new Date().toISOString().slice(0, 19).replace('T', ' ');
    const tag = `[${stamp}] sent: email=${out.email||'skip'} wa=${out.whatsapp||'skip'}`;
    await control.query(
      `UPDATE invoices SET notes = COALESCE(notes, '') || E'\n' || $1, updated_at=NOW() WHERE id=$2`,
      [tag, invoice.id]
    );
  } catch (_) {}
  return out;
}

/** Run one full sweep cycle. Safe to call manually from a super-admin API. */
async function runOnce() {
  if (_running) return { skipped: 'already running' };
  _running = true;
  const out = { scanned: 0, created: 0, sent: 0, errors: [] };
  try {
    const daysBefore = parseInt((await control.getSetting('AUTO_INVOICE_DAYS_BEFORE')) || '0', 10);
    if (!daysBefore || daysBefore < 1) {
      out.skipped = 'AUTO_INVOICE_DAYS_BEFORE not set (>=1 enables)';
      return out;
    }
    const sendEmail = (await control.getSetting('AUTO_INVOICE_SEND_EMAIL')) === '1';
    const sendWa    = (await control.getSetting('AUTO_INVOICE_SEND_WA'))    === '1';

    const tenants = await control.query(
      `SELECT id, name, slug, contact_email, contact_phone, package_id,
              current_period_start, current_period_end, status
         FROM tenants
        WHERE status IN ('active','trialing','past_due')
          AND current_period_end IS NOT NULL
          AND current_period_end <= NOW() + ($1 || ' days')::interval
          AND current_period_end >= NOW() - INTERVAL '2 days'`,
      [String(daysBefore)]
    );
    out.scanned = tenants.rows.length;

    for (const t of tenants.rows) {
      try {
        // Has an invoice already been created for this period?
        const ex = await control.query(
          `SELECT id, number FROM invoices
            WHERE tenant_id=$1 AND period_end::date = $2::date
              AND status IN ('pending','paid','failed')
            LIMIT 1`,
          [t.id, t.current_period_end]
        );
        let invoice;
        if (ex.rows.length) {
          invoice = { id: ex.rows[0].id, number: ex.rows[0].number, _existing: true };
        } else {
          invoice = await _createInvoiceForTenant(t);
          out.created++;
        }

        // Only send for fresh invoices to avoid spamming
        if (!invoice._existing && (sendEmail || sendWa)) {
          const r = await _sendInvoice(t, invoice, { email: sendEmail, whatsapp: sendWa });
          if (r.email === 'sent' || r.whatsapp === 'sent') out.sent++;
        }
      } catch (e) {
        out.errors.push({ tenant: t.slug, err: String(e.message || e).slice(0, 200) });
      }
    }
    return out;
  } finally {
    _running = false;
  }
}

function startSweep() {
  if (_started) return;
  _started = true;
  // First run after 5 min to let server warm up
  setTimeout(() => runOnce().catch(e => console.warn('[saasInvoiceAutoGen]', e.message)), 5 * 60 * 1000);
  setInterval(() => runOnce().catch(e => console.warn('[saasInvoiceAutoGen]', e.message)), RUN_EVERY_MS);
  console.log('[saasInvoiceAutoGen] sweep started (every 6h)');
}

module.exports = { runOnce, startSweep, _sendInvoice, _genInvoiceNumber };
